name: Recover .env File

on: 
  workflow_dispatch # Permite rodar manualmente quando precisar

jobs:
  recover-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar arquivo .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env

      - name: Mostrar conteúdo do .env (Apenas para conferência)
        run: cat .env
