name: Recuperar .env

on:
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  recover-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar arquivo .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env

      - name: Verificar se o arquivo .env foi criado
        run: |
          if test -f ".env"; then echo ".env foi criado com sucesso."; else echo "Erro ao criar .env"; fi

      - name: Fazer o upload do .env como artefato
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env
